server:
  port: 8081
spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/SP_AM?
    username: root
    password: 
mybatis:
  type-aliases-package: com.example.demo.vo;